### ISSUE TITLE
Packaging problem

### ISSUE THREAD

**Issue by ElizabethYupyy** [CrystalVapor/Crystal-Recoil-System#4]
Hello! I was tried to package project for windows, but i was received this error.
(tested on UE5.4 and UE5.5 prev)

[39/69] Compile [x64] Module.AdvancedSessions.2.cpp
 Compile [x64] CRRecoilPattern.cpp: Exited with error code 2 . The build will fail.
 Compile [x64] CRRecoilPattern.cpp: WorkingDirectory D:\EpicGames\UE_5.4\Engine\Source
 Compile [x64] CRRecoilPattern.cpp: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe @"D:\Projects\rtr\Plugins\Crystal-Recoil-System-main\Intermediate\Build\Win64\x64\UnrealGame\Shipping\CrystalRecoil\CRRecoilPattern.cpp.obj.rsp"
[40/69] Compile [x64] CRRecoilPattern.cpp
D:\Projects\rtr\Plugins\Crystal-Recoil-System-main\Source\CrystalRecoil\Private\CRRecoilPattern.cpp(43): error C2039: 'IsDataValid': is not a member of 'UCRRecoilPattern'
D:\Projects\rtr\Plugins\Crystal-Recoil-System-main\Source\CrystalRecoil\Public\CRRecoilPattern.h(36): note: see declaration of 'UCRRecoilPattern'
D:\Projects\rtr\Plugins\Crystal-Recoil-System-main\Source\CrystalRecoil\Private\CRRecoilPattern.cpp(45): error C2653: 'Super': is not a class or namespace name
[41/69] Compile [x64] CRRecoilComponent.cpp
[42/69] Compile [x64] UpdateSessionCallbackProxyAdvanced.cpp

looks like (43) line in CRRecoilPattern is deprecated, i tried to update the validation, but nothing, anyway error 

if u will have time please update the plugin for ue 5.4, thanks! ;)

**Comment by CrystalVapor** [comment]
I'll try to solve that, I create this plugin for 5.2 firstly, and i haven't examined my code when upgraded to 5.4
Thank you one more time for keeping help me to improve this plugin!

**Comment by ElizabethYupyy** [comment]
Thank u! i will wait ;D also thx for sharing this plugin, it's really good, i am making a simple not commercial combat game for me and my friends (using your plugin for recoil)

**Comment by CrystalVapor** [comment]
Okay i've find out what's annoying you
It's not about deprecated function but editor-only methods
briefly, IsDataValid is an editor-only methods to validate data when you're save or compile your blueprint assets, it's only make senses in editor, avoid keep this useless function in release version, we will cut it when we're packaging game
the trick is, we will surrounding them with macros:
![image](https://github.com/user-attachments/assets/1f8b1e0d-2306-45a9-9a54-d22510e2305d)
If you changing your build target to Shipping rather than Editor/DebugGame you will noticed the contents in #if will be spoiled.
I've added these macro and changed the deprecated method to new version.

**Comment by ElizabethYupyy** [comment]
thank u! the errors is fixed, but another one appeared and it seems even more complicated 

------ Building 4 action(s) started ------
[1/4] Compile [x64] CRSpreadRecoilComponent.cpp
[2/4] Compile [x64] Module.CrystalRecoil.cpp
[3/4] Link [x64] arsct-Win64-Shipping.exe
   Creating library D:\Projects\rtr\Binaries\Win64\arsct-Win64-Shipping.lib and object D:\Projects\rtr\Binaries\Win64\arsct-Win64-Shipping.exp
Module.CrystalRecoil.cpp.obj : error LNK2019: link to unresolved external symbol "public: float __cdecl UCRSpreadRecoilComponent::GetRecoilHeat(void)const " (?GetRecoilHeat@UCRSpreadRecoilComponent@@QEBAMXZ) in function "public: static void __cdecl UCRSpreadRecoilComponent::execGetRecoilHeat(class UObject *,struct FFrame &,void * const)" (?execGetRecoilHeat@UCRSpreadRecoilComponent@@SAXPEAVUObject@@AEAUFFrame@@QEAX@Z).
D:\Projects\rtr\Binaries\Win64\arsct-Win64-Shipping.exe : fatal error LNK1120: unresolved externals: 1
 Link [x64] arsct-Win64-Shipping.exe: Exited with error code 1120 . The build will fail.
 Link [x64] arsct-Win64-Shipping.exe: WorkingDirectory D:\EpicGames\UE_5.4\Engine\Source
 Link [x64] arsct-Win64-Shipping.exe: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\link.exe @"D:\Projects\rtr\Intermediate\Build\Win64\x64\arsct\Shipping\arsct-Win64-Shipping.exe.rsp"
 
 i was searched some info in google but nothing, also i tried to add SpreadRecoilComponent to my build.cs but it didn't help, any ideas what i need to do to fix that error?... thx!

**Comment by CrystalVapor** [comment]
I have no condition to build a shipping pack at this time, so i'm just guessing what's wrong
i think this is caused by i set this method as 'inline', you can remove inline and try again

**Comment by CrystalVapor** [comment]
![image](https://github.com/user-attachments/assets/aed0006c-62c2-4c5d-a2c5-6f2a648f613c)
Fixed on my machine
@See: commit#1099356

**Comment by ElizabethYupyy** [comment]
thank u very very much! it's working ;DD
